### ISSUE TITLE
Price format does not edited in product detail page.

### ISSUE THREAD

**Issue by msliman** [lillik/magento2-price-decimal#10]

**Comment by lillik** [comment]
Hi @msliman, what does mean not edited. Can you provide more details to this issue?

**Comment by msliman** [comment]
@lillik I increased decimal point in price, so I want price to become like(12.550) without (12.55). It changed in products display in front end except  product page which display all details about product.
![product_page](https://cloud.githubusercontent.com/assets/3694009/25771486/e01280d4-325b-11e7-9adb-3e532c2c56bd.png)

-Also, I cant increase the decimal point shipping, orders, taxes. It just increases the price for products only.

-Also, How can I increase decimal point for both frontend and backend. see [https://github.com/lillik/magento2-price-decimal/issues/9](url)

**Comment by lillik** [comment]
Did you clear cache.
If **Full Page Cache** is enable on you website, please clear full page cache.
Best regards,

**Comment by lillik** [comment]
Issue will be closed.
