### ISSUE TITLE
Not working in product page

### ISSUE THREAD

**Issue by kushagradaharwal** [lillik/magento2-price-decimal#12]
Hi,
Price decimal is not updating in product details page and also in admin side many place its not working,
Please reply

**Comment by kushagradaharwal** [comment]
![image](https://user-images.githubusercontent.com/7345611/30251072-8daf81a0-9676-11e7-8745-898a3e217b85.png)


![image](https://user-images.githubusercontent.com/7345611/30251074-9cdcde20-9676-11e7-8412-ee3afc110de6.png)

**Comment by lillik** [comment]
Did you clear the cache?
Remove all files from:
- var/cache
- var/page_cache
