### ISSUE TITLE
Remove ,00

### ISSUE THREAD

**Issue by inelukipg** [lillik/magento2-price-decimal#14]
Hi,

I have not Iinstalled yet, but is it possible to just remove decimals if they're just zeros? 
"50,00" => 50
"50,20" => 50,20

**Comment by lillik** [comment]
Hi, no it not possible. The module can remove decimal for all value:
"50.00" => "50"
"50.20" => "50"

I'll add this feature in to next version.

**Comment by inelukipg** [comment]
Hi,
Ok, sounds great!

**Comment by adarshkhatri** [comment]
I am also in need of removing `.00`. 
"50.00" => "50"
"50.20" => "50.20"
It looks this feature is still not added yet.
Would love to have this feature.

**Comment by adarshkhatri** [comment]
I have created a simple extension for this. Give it a try: https://github.com/adarshkhatri/price-decimal-magento2
