### ISSUE TITLE
Magento does not work with this plugin

### ISSUE THREAD

**Issue by eyesoverrun** [lillik/magento2-price-decimal#17]
Does not work with Magento 2.1.8
This is the error in var/log/system.log:
`[2017-09-28 12:51:41] main.CRITICAL: Strict Notice: Lillik\PriceDecimal\Model\Plugin\PriceFormatPluginAbstract and Lillik\PriceDecimal\Model\PricePrecisionConfigTrait define the same property ($moduleConfig) in the composition of Lillik\PriceDecimal\Model\Plugin\PriceFormatPluginAbstract. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /var/www/vhosts/site/vendor/lillik/magento2-price-decimal/Model/Plugin/PriceFormatPluginAbstract.php on line 51 [] []`

**Comment by lillik** [comment]
@eyesoverrun what is your PHP version?

**Comment by eyesoverrun** [comment]
It's PHP 5.6

**Comment by lillik** [comment]
Fixed. Please Update module via composer.

**Comment by eyesoverrun** [comment]
Now I have another problem.
The prices are rounded despite the backend price is correct and a javascript when loading the product page rounds to 2 decimal places.
![out-2](https://user-images.githubusercontent.com/17945529/31115764-d021d484-a823-11e7-934b-7182e9f053bd.gif)
