### ISSUE TITLE
how do i can install the extension

### ISSUE THREAD

**Issue by mustafa449** [lillik/magento2-price-decimal#18]
Hi Dear,
Could you please explain me how do i install the extension. I am new to magento.
where i should place the files and what i should do exactly ?
thank you very much

**Comment by lillik** [comment]
Install Composer, find instruction here:
https://getcomposer.org/doc/00-intro.md

Got to root directory of your magento project and execut this command
`composer require lillik/magento2-price-decima`
Or this if you downloaded `composer.phar` into you magento directory
`php composer.phar require lillik/magento2-price-decima`

**Comment by mustafa449** [comment]
thank you very much, so just without doing any think, just i should run the following command from my root directory  composer require lillik/magento2-price-decima and thats it ???
it will work on my magento 2 after that right ?

**Comment by mustafa449** [comment]
E Spasepo Polshow Prat za panemanee

**Comment by lillik** [comment]
After was installed module you need to Enable Module, find more information about this here:
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html

Don't forget to execute following commands:
`php bin/magento setup:upgrade`
`php bin/magento cache:clean`
