### ISSUE TITLE
Update price error with no decimals

### ISSUE THREAD

**Issue by jadeg81** [lillik/magento2-price-decimal#21]
Hi i have tried your extension with no decimals, congratulations it works very well.

In the storefront works great, but maybe there is a problem with backend.

I have imported products via CSV and the price in backend is correctly showed with no decimals. But when i open and update product, price are updated with error.

For example: I have a price for a product of 1,200 € (one thousand two hundred euro), so the price is updated to 1 € when product is saved. It seems that with no decimals there is a precision error. To update correctly i need to set price to "1200.00".

Can you confirm, or not, that it is an issue?

Thanks in advance.

**Comment by lillik** [comment]
I think that this is the issue of import product module.
