### ISSUE TITLE
Thousands

### ISSUE THREAD

**Issue by alxgarza** [lillik/magento2-price-decimal#22]
If you have a product with it's price in the thousands, when you modify say of it's attributes  the price will be modified and 3 digits will be drop.

Ex: Price: $15,000
After modifying an attribute: Price: $15

**Comment by ludcl** [comment]
Same issue here. Using Magento 2.2.2
@alxgarza , did you solved the issue or did you found any workaround?

**Comment by ludcl** [comment]
I've reverted changes in a previous commit in etc/di.xml file. Changing lines 5 and 6 to:
`    <preference for="Magento\Framework\Locale\CurrencyInterface" type="Magento\Framework\Locale\Currency" />
    `
allows the extension to work fine at frontend and do nothing at backend.
It's not a solution, but it at least show the desired result to customers without the bad pricing issue :smile:

**Comment by sadon** [comment]
I am confirm the issue with modifying
 $15,000 -> 15 
in all currency fields with "," as separator you got /1000 values.

From admin point of view you can change adm in-user language that use "." as separator :)

**Comment by sadon** [comment]
@ludcl 
your solution unfortunately didn't work:

`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught TypeError: Argument 1 passed to Lillik\PriceDecimal\Model\Plugin\Currency::beforeToCurrency() must be an instance of Lillik\PriceDecimal\Model\Currency, instance of Magento\Framework\Currency\Interceptor given,`

**Comment by antonydu-cd** [comment]
Solution:
Lillik/PriceDecimal/Model/Plugin/PriceFormatPluginAbstract.php :
```

protected $_localeResolver;

    /**
     * @param \Lillik\PriceDecimal\Model\ConfigInterface $moduleConfig
     */
    public function __construct(
        ConfigInterface $moduleConfig,
        \Magento\Framework\Locale\ResolverInterface $localeResolver
    ) {
        $this->moduleConfig  = $moduleConfig;
        $this->_localeResolver = $localeResolver;
    }
```

Lillik/PriceDecimal/Model/Plugin/Local/Format.php:

```
private const JAPAN_LOCALE_CODE = 'ja_JP';
public function aroundGetNumber(
        $subject, 
        \Closure $proceed,
        $value
    ){
        $precision = $this->getPricePrecision();

        if ($value === null) {
            return null;
        }

        if (!is_string($value)) {
            return (float)$value;
        }

        //trim spaces and apostrophes
        $value = preg_replace('/[^0-9^\^.,-]/m', '', $value);

        $separatorComa = strpos($value, ',');
        $separatorDot = strpos($value, '.');

        if ($separatorComa !== false && $separatorDot !== false) {
            if ($separatorComa > $separatorDot) {
                $value = str_replace(['.', ','], ['', '.'], $value);
            } else {
                $value = str_replace(',', '', $value);
            }
        } elseif ($separatorComa !== false) {
            $locale = $this->_localeResolver->getLocale();
            /**
             * It's hard code for Japan locale.
             * Comma separator uses as group separator: 4,000 saves as 4,000.00
             */
            $value = str_replace(
                ',',
                $locale === self::JAPAN_LOCALE_CODE || $this->getConfig()->isEnable() && $precision == 0 ? '' : '.',
                $value
            );
        }

        return (float)$value;
    }
```

**Comment by nayanchamp** [comment]
> Solution:
> Lillik/PriceDecimal/Model/Plugin/PriceFormatPluginAbstract.php :
> 
> ```
> 
> protected $_localeResolver;
> 
>     /**
>      * @param \Lillik\PriceDecimal\Model\ConfigInterface $moduleConfig
>      */
>     public function __construct(
>         ConfigInterface $moduleConfig,
>         \Magento\Framework\Locale\ResolverInterface $localeResolver
>     ) {
>         $this->moduleConfig  = $moduleConfig;
>         $this->_localeResolver = $localeResolver;
>     }
> ```
> 
> Lillik/PriceDecimal/Model/Plugin/Local/Format.php:
> 
> ```
> private const JAPAN_LOCALE_CODE = 'ja_JP';
> public function aroundGetNumber(
>         $subject, 
>         \Closure $proceed,
>         $value
>     ){
>         $precision = $this->getPricePrecision();
> 
>         if ($value === null) {
>             return null;
>         }
> 
>         if (!is_string($value)) {
>             return (float)$value;
>         }
> 
>         //trim spaces and apostrophes
>         $value = preg_replace('/[^0-9^\^.,-]/m', '', $value);
> 
>         $separatorComa = strpos($value, ',');
>         $separatorDot = strpos($value, '.');
> 
>         if ($separatorComa !== false && $separatorDot !== false) {
>             if ($separatorComa > $separatorDot) {
>                 $value = str_replace(['.', ','], ['', '.'], $value);
>             } else {
>                 $value = str_replace(',', '', $value);
>             }
>         } elseif ($separatorComa !== false) {
>             $locale = $this->_localeResolver->getLocale();
>             /**
>              * It's hard code for Japan locale.
>              * Comma separator uses as group separator: 4,000 saves as 4,000.00
>              */
>             $value = str_replace(
>                 ',',
>                 $locale === self::JAPAN_LOCALE_CODE || $this->getConfig()->isEnable() && $precision == 0 ? '' : '.',
>                 $value
>             );
>         }
> 
>         return (float)$value;
>     }
> ```

Yes, this works when price more than a thousand.

**Comment by lillik** [comment]
Fixed.
