### ISSUE TITLE
Product view page decimal not working display default two decimal

### ISSUE THREAD

**Issue by Suresh-Chikani** [lillik/magento2-price-decimal#24]
Hello lillik,
I am use Magento ver. 2.1.7. I have set Decimal Length 3 But When i am open product view page, It's display only two decimal. Please suggest if any solution. I have attach screen shot please check it.

**Product List Page View**
![product_list](https://user-images.githubusercontent.com/35174609/34734786-15edb48a-f593-11e7-8db8-2b5f6cee9514.png)

**Product View Page**
![product_page](https://user-images.githubusercontent.com/35174609/34734787-162c0636-f593-11e7-8452-4e612182ca86.png)

**Comment by kamilmaliszewski** [comment]
Hi ! I have similar bug for Magento 2.2. In my case was error on price-utilis.js. JS method "toFixed" has hardcoded 2 and on the detail view the price was replaced -> not values from configuration. `am.toFixed(precision)` helped me. Here is all method. Modify is only one line.

       `function formatPrice(amount, format, isShowSign) {
        var s = '',precision, integerRequired, decimalSymbol, groupSymbol, groupLength, pattern, i, pad, j, re, r, am;
        format = _.extend(globalPriceFormat, format);

        // copied from price-option.js | Could be refactored with varien/js.js

        precision = isNaN(format.requiredPrecision = Math.abs(format.requiredPrecision)) ? 2 : format.requiredPrecision;
        integerRequired = isNaN(format.integerRequired = Math.abs(format.integerRequired)) ? 1 : format.integerRequired;
        decimalSymbol = format.decimalSymbol === undefined ? ',' : format.decimalSymbol;
        groupSymbol = format.groupSymbol === undefined ? '.' : format.groupSymbol;
        groupLength = format.groupLength === undefined ? 3 : format.groupLength;
        pattern = format.pattern || '%s';

        if (isShowSign === undefined || isShowSign === true) {
            s = amount < 0 ? '-' : isShowSign ? '+' : '';
        } else if (isShowSign === false) {
            s = '';
        }
        pattern = pattern.indexOf('{sign}') < 0 ? s + pattern : pattern.replace('{sign}', s);

        // we're avoiding the usage of to fixed, and using round instead with the e representation to address
        // numbers like 1.005 = 1.01. Using ToFixed to only provide trailig zeroes in case we have a whole number
        i = parseInt(
                amount = Number(Math.round(Math.abs(+amount || 0) + 'e+' + precision) + ('e-' + precision)),
                10
            ) + '';
        pad = i.length < integerRequired ? integerRequired - i.length : 0;

        i = stringPad('0', pad) + i;

        j = i.length > groupLength ? i.length % groupLength : 0;
        re = new RegExp('(\\d{' + groupLength + '})(?=\\d)', 'g');

        // replace(/-/, 0) is only for fixing Safari bug which appears
        // when Math.abs(0).toFixed() executed on '0' number.
        // Result is '0.-0' :(

        am = Number(Math.round(Math.abs(amount - i) + 'e+' + precision) + ('e-' + precision));
        r = (j ? i.substr(0, j) + groupSymbol : '') +
            i.substr(j).replace(re, '$1' + groupSymbol) +
            (precision ? decimalSymbol + am.toFixed(precision).replace(/-/, 0).slice(2) : '');

        return pattern.replace('%s', r).replace(/^\s\s*/, '').replace(/\s\s*$/, '');
    }`

**Comment by lillik** [comment]
Was fixed with last commit. Thx @cdiacon
