### ISSUE TITLE
Price change in admin when save product

### ISSUE THREAD

**Issue by allinvinod** [lillik/magento2-price-decimal#27]
I have installed this extension which is working fine on frontend. But When I am saving the product in admin, product price changed from 7,499 to 7.
I am using Magento 2.1.8

**Comment by cdiacon** [comment]
@allinvinod can you post the settings you have for the price decimal ?

I think you can get this only if you have Decimal Length = 0, you should use the 3 in your case.

**Comment by allinvinod** [comment]
Yes, I have Decimal Length = 0

**Comment by cdiacon** [comment]
@allinvinod you will still have the 7,499 saved in database but the displayed value will be 7, it's the matter of how many decimals you want to show.

**Comment by maettuw** [comment]
I have a similar problem. The price is correct on first save of a product. 
If I change something other like SKU, then the price will be rounded down to $10 from starting $10,900. The price will also be changed in frontend so it is saved to database.

**Comment by allinvinod** [comment]
I am not using this extension. Because the issue was not fixed.

**Comment by maettuw** [comment]
@allinvinod do you have an other extension for the same purpose?

**Comment by allinvinod** [comment]
No, I don't have another extension.

I have fixed the issue to edit precision value from catalog js.

Override below JS in your theme:

vendor/magento/module-catalog/view/base/web/js/price-utils.js

and update precision value from 2 to 0.

var globalPriceFormat = {
        *requiredPrecision: 0,*
        integerRequired: 1,
        decimalSymbol: ',',
        groupSymbol: ',',
        groupLength: ','
    };


Regards,
Vinod

**Comment by lillik** [comment]
Thanks @allinvinod.

**Comment by lillik** [comment]
Theme Issue.

**Comment by fsrojash** [comment]
I have this same issue, i try to override vendor/magento/module-catalog/view/base/web/js/price-utils.js into this route -> my-theme/Magento_Catalog/web/js/price-utils.js, and setting requiredPrecision = 0... But, it's not working, it still changing the price from 7,499 to 7... Any thoughts?

**Comment by amcastror** [comment]
Hi @fsrojash, were you able to fix this? Thanks a lot.

**Comment by fsrojash** [comment]
Hi @amcastror, nop, still with the issue...So, to keep a price like $7.499 i have to delete the comma before saving...

**Comment by lillik** [comment]
Fixed in version 1.0.6
