### ISSUE TITLE
Admin product page show 4 decimal failure

### ISSUE THREAD

**Issue by linzw07** [lillik/magento2-price-decimal#31]
Admin product page show 4 decimal failure, and it keeps showing 2 decimal. So when I save the product price in admin it will change the product price to 2 decimal in db so frontend product page it will only show  2 decimal  price

**Comment by brampta** [comment]
yep Im having the same issue, no matter how I configure the extension it will not change decimals in the admin, they are rounded to 2 and so when I save the product it erases my 4 digits values I have in the DB. really trying to find a solution for that but none so far.

**Comment by lillik** [comment]
Fixed
