### ISSUE TITLE
Other precision for price unit than for totals

### ISSUE THREAD

**Issue by verhaeghep** [lillik/magento2-price-decimal#32]
Is it possible to have another price precision (e.g. 4) for price unit than the precision (e.g. 2) for price totals?

**Comment by lillik** [comment]
Do we talk about checkout page?

**Comment by verhaeghep** [comment]
Yes, the cart and checkout page.

**Comment by lillik** [comment]
Your requirement was added into TODO list.
Thanks a lot.
