### ISSUE TITLE
Price issue on Magento 2.2.4

### ISSUE THREAD

**Issue by fsrojash** [lillik/magento2-price-decimal#33]
When i expect a see a product with a price of $10 the value is changed to "$0.010". This issue appears after an upgrade from Magento 2.1.13 to 2.2.4.

Simple product with the issue -> http://159.65.178.226/demo-simple.html

**Comment by lillik** [comment]
I can not reproduce this issue. Pleas try this after upgrade.
php bin/magento cache:clean;
php bin/magento cache:flush;
php bin/magento index:reindex;
php bin/magento setup:upgrade;
php bin/magento setup:di:compile;
php bin/magento setup:static-content:deploy;
