### ISSUE TITLE
Problem With Thousands

### ISSUE THREAD

**Issue by Nickpap21** [lillik/magento2-price-decimal#34]
Hello,

When choosing thousands as a price in backend (ex 2511€) the result is 2,411 , as the thousands separator is the comma. Due to this the final price with the extension enabled is 2€. Do you have any fix for this? I saw that someone has already issued this, but there wasn't a solution. 

Thank you

**Comment by amcastror** [comment]
Hi @Nickpap21 did you find a fix for this? Thanks.

**Comment by lillik** [comment]
Hi,
@Nickpap21  and @amcastror, please let me know what Magento Version do you use? I would like to reproduce this issue. 
Thanks a lot.

**Comment by amcastror** [comment]
Hi @lillik, I'm on 2.2.3. I looked around a bit and I couldn't see the admin using price-utils.js (there's another thread pointing it as a posible fix, which didn't work for me).

**Comment by lillik** [comment]
Ok, let me see how can I fix this issue. I'll come with a feedback.

**Comment by lillik** [comment]
Fixed.
