### ISSUE TITLE
Remove only zero decimal option?

### ISSUE THREAD

**Issue by Oliver7792** [lillik/magento2-price-decimal#35]
Hi Lilian,
Can you add new option for this extension. Sometimes, we want to remove only zero numbers from decimal. Now, Does it remove all decimal numbers?. Thank you!

**Comment by lillik** [comment]
Yout requirement was added into TODO list.
Thanks a lot.

**Comment by ultrazeus** [comment]
@lillik Any idea when this would be added? This would be a great feature.

**Comment by TomVDH** [comment]
Seems like you have all but abandoned this project.

**Comment by rocky2305** [comment]
Admin catalog product edit is not saving/displayed 4 decimals value at product level, can you let me know here how can that be achieved?
