### ISSUE TITLE
Missing required argument $options of Lillik\PriceDecimal\Model\Currency.

### ISSUE THREAD

**Issue by kevintseng** [lillik/magento2-price-decimal#36]
Great contribution, thank you! But I got this exception after installation:

`1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $options of Lillik\PriceDecimal\Model\Currency.

Exception #0 (BadMethodCallException): Missing required argument $options of Lillik\PriceDecimal\Model\Currency.
#0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Lillik\\PriceDec...', Array, Array)
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Lillik\\PriceDec...', Array, Array)
#2 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Lillik\\PriceDec...')
#3 /var/www/html/app/code/Magestore/Affiliateplus/Helper/HelperAbstract.php(216): Magento\Framework\ObjectManager\ObjectManager->get('Lillik\\PriceDec...')`

**Comment by lillik** [comment]
@kevintseng thx for your report.
The issue was fixed in version 1.0.4 (last version at this moment). 
Please use the version 1.0.4.

Best regards.
