### ISSUE TITLE
Activate per website

### ISSUE THREAD

**Issue by ultrazeus** [lillik/magento2-price-decimal#40]
Hi,

First of all great extension. 
I would like to know if I can activate the extension per website. For B2C customer I want round prices in the frontend but for the B2B website the decimals are really needed. 

Thanks

**Comment by lillik** [comment]
Hi,
Thanks. Yes, you can activate per website. At the moment, this feature was developed only into the dev-master branch. Please use code from the dev-master branch. ASAP I'll release this feature in a new release version.
