### ISSUE TITLE
Backend update product error 1,000 to 1

### ISSUE THREAD

**Issue by vinazoom** [lillik/magento2-price-decimal#41]
I use on magento 2.1.14 and bellow not have this issue.
On magento 2.1.16 example i set precision = 0
On product set price = 990000
First save ok, second edit, the price auto add "," to 990,000
After save, the price  was change to 990

This extension is very helpful, thanks for developers. 
I hope this issue will be fix soon.

**Comment by estebanbocic** [comment]
can confirm this issue when updating via backend this happens on special price and normal price. Please fix this and keep going with the good work!

**Comment by vinazoom** [comment]
it affects both normal and special price

On edit an exist product, it show
![image](https://user-images.githubusercontent.com/15831628/60796337-5f267400-a197-11e9-82a6-a20a41ca3ffe.png)

After save

![image](https://user-images.githubusercontent.com/15831628/60796652-00adc580-a198-11e9-96fa-8a5a58592a1a.png)

1,390,000 round to 1. 
If want to work fine, i will add .00 to price, Exp: 1,390,000.00

**Comment by lillik** [comment]
Fixed.
