### ISSUE TITLE
Decimal config not used when running in cron scope

### ISSUE THREAD

**Issue by juhanihaapala** [lillik/magento2-price-decimal#43]
If price calculations are done in crontab scope the configured decimal is not used. 

I fixed the issue based on #42 in [my fork](https://github.com/Codaone/magento2-price-decimal/commit/79b020cc6926fab6621749b0451e641584e79daf) and was about to make pull request, but then realized there is in total 8 different scopes so maybe this is not correct way to fix the issue.

**Comment by lillik** [comment]
@juhanihaapala please pull your code to be merged. Thanks a lot for your help @juhanihaapala and @zamoroka
