### ISSUE TITLE
Magento 2.3 adminhtml inputs showing rounded value

### ISSUE THREAD

**Issue by raulsinapsis** [lillik/magento2-price-decimal#46]
We have tried this extension in Magento 2.3 project (2.3.1 version, to be exact) cause we need to set up 4 decimals for EUR currency

It is working fine, we can save prices with 4 decimals and they are registered fine in database. In frontend all prices are being displayed with 4 decimals... but there is one big problem. If you open edit product page in backoffice all values are visually rounded to 2 decimals, so if you save the product, the rounded value is sent to form & the 4 decimal value is lost

Is this some bug introduced in newer versions of Magento2?

**Comment by jrod1982** [comment]
Did you ever find a solution for this? We need to retype the price every time we edit a product, it's become rather annoying.

**Comment by raulsinapsis** [comment]
Yeah
Check this https://magento.stackexchange.com/questions/281899/magento2-admin-price-inputs-are-rounding-value-to-2-decimals

**Comment by jrod1982** [comment]
Thanks for sharing! I'm a novice and can't get his module to work. Any chance you can share your completed module with me?

**Comment by lillik** [comment]
Hi @jrod1982  and  @raulsinapsis , in the next future, I'll fix the issue related to Magento 2.3.x version. Thanks a lot for your feedback.

**Comment by camalolo** [comment]
Hello, this issue still shows up with Magento 2.3.6 and lillik/magento2-price-decimal 1.0.7
