### ISSUE TITLE
Problem in installation 

### ISSUE THREAD

**Issue by muhammedomar32** [lillik/magento2-price-decimal#51]
Dear 
can you help me 
when i download the module and added in /var/www/html/app/code/lillik/magento2-price-decimal 
after run bin/magento setup:di:compile
get this error 
![2020-07-10_160913](https://user-images.githubusercontent.com/52316549/87158127-e8e7b080-c2c7-11ea-8257-c56d6891c0c6.jpg)
Why??
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 78.5 MiBPHP Fatal error:  Trait 'Lillik\PriceDecimal\Model\PricePrecisionConfigTrait' not found in /var/www/html/app/code/lillik/magento2-price-decimal/Ui/DataProvider/Product/Modifier/Price.php on line 21

**Comment by muhammedomar32** [comment]
@lillik  please advice 
?

**Comment by alvaromoralesa** [comment]
try composer update

**Comment by lillik** [comment]
User composer to install this module. 
But if you prefer to keep module into app/code, please rename folder "/var/www/html/app/code/lillik/magento2-price-decimal" to "/var/www/html/app/code/Lillik/PriceDecimal"
