### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mohammedalrefai** [lillik/magento2-price-decimal#55]
hello lillik,
is it possible that the plugin do the calculation with 4 decimals and show the result with 2?
thanks.

**Comment by Patriboom** [comment]
Reading the infos, I don't think the plugin does any calculation.  It only cuts or add decimals according to your selection. 
(I'm not sure, newly entered in this project.)

**Comment by lillik** [comment]
@Patriboom is right, the plugin does not do any calculation.
