### ISSUE TITLE
How to show price format also in the backend ?

### ISSUE THREAD

**Issue by msliman** [lillik/magento2-price-decimal#9]

**Comment by lillik** [comment]
Please take a look now.
Was fixed with last update version 1.0.1

**Comment by brampta** [comment]
I am testing your module on Magento ver. 2.2.5 but the prices in the backend still have only 2 digits. does not seem to work for me.

**Comment by VaporFan** [comment]
In Admin Product Grid, the price was correctly formatted. I wonder how to apply this neat effect to Special Price and also in Product Edit page. In Product Edit page, the prices still have two decimals. Thanks for your effort.

[https://imgur.com/a/IPvYvAv](https://imgur.com/a/IPvYvAv)
